services:
  migrator:
    container_name: dl-migrator
    image: ${DOCKER_REGISTRY_URL}/migrator
    build:
      dockerfile: .
    env_file:
      - .env
    hostname: ${MIGRATOR_HOST}
    restart: always
    depends_on:
      - database
  database:
    container_name: dl-database
    image: postgres:16-alpine
    restart: always
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/database/data:/var/lib/postgresql/data
      - ./docker/database/scripts:/docker-entrypoint-initdb.d
      - ./logs/database:/var/log/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -p ${DB_PORT}
