services:
  migrator:
    container_name: dl-migrator
    image: ${DOCKER_REGISTRY_URL}/migrator-bun
    build:
      context: .
    env_file:
      - .env
    hostname: ${MIGRATOR_HOST}
    volumes:
      - ./files:/app/files
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  database:
    container_name: dl-database
    image: postgres:16-alpine
    restart: always
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -p ${DATABASE_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/database/data:/var/lib/postgresql/data
      - ./docker/database/scripts:/docker-entrypoint-initdb.d
      - ./logs/database:/var/log/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -p ${DATABASE_PORT}
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
  redis:
    container_name: dl-redis
    image: redis/redis-stack-server:7.2.0-v6
    restart: always
    hostname: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -p ${REDIS_PORT} PING | grep -q PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./docker/redis/data:/data
      - ./logs/redis:/var/log/redis
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD}
      REDIS_ARGS: --port ${REDIS_PORT} --logfile /var/log/redis/redis-server.log --dbfilename dump.rdb --dir /data --requirepass ${REDIS_PASSWORD}
